<script lang="ts">
  import {
    LayoutDashboard,
    ChartNoAxesCombined,
    ArrowDownToLine,
    ArrowRight,
    Copy,
    Download,
    Eye,
    EyeOff,
    History,
    Link,
    LogIn,
    LogOut,
    Monitor,
    Moon,
    QrCode,
    RefreshCw,
    Send,
    Share2,
    ShieldCheck,
    SlidersHorizontal,
    Smartphone,
    Sun,
    Trash2,
    Upload,
    UserRound,
    Users,
    X,
    LockKeyhole,
    ChevronDown,
  } from "@lucide/svelte";

  const icons = {
    Overview: LayoutDashboard,
    Traffic: ChartNoAxesCombined,
    Send,
    Receive: ArrowDownToLine,
    History,
    Settings: SlidersHorizontal,
    Account: UserRound,
    Devices: Smartphone,
    Users,
    Upload,
    Lock: LockKeyhole,
    Arrow: ArrowRight,
    Sun,
    Moon,
    Monitor,
    ChevronDown,
    Eye,
    EyeOff,
    Copy,
    Share: Share2,
    Download,
    Revoke: Trash2,
    Refresh: RefreshCw,
    SignOut: LogOut,
    Close: X,
    LogIn,
    QRCode: QrCode,
    Shield: ShieldCheck,
    Link,
  };
  let { name, size = 20 }: { name: keyof typeof icons; size?: number } = $props();
  const Glyph = $derived(icons[name]);
</script>

<Glyph {size} strokeWidth={1.75} aria-hidden="true" focusable="false" />
